name: Deploy to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: node setup
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: set AWS creds
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS-REGION: us-east-1
      - name: copy to s3
        run: aws s3 sync ./build/. s3://mysolarsystem